baseURL = "https://descubre.virgulilla.com"

defaultContentLanguage = "es"
[languages]
[languages.es]
  contentDir = "content/es"
  title = "#DescubriendoPalabras"
  languageCode = "es-es" # RSS

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML", "JSON"]
